user www-data;

# nb de processus de travail a lancer -> depend donc auto
worker_processes auto;

# chaque processus worker pourra gerer jusqu’a 1024 connexions en meme temps
events {
	worker_connections 1024;
}

http {

    # on charge la liste des types MIME (poru connaitre le type du fichier css, html...)

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

    # pour ameliorer l’envoi des fichiers statiques
	sendfile on;

    # une connexion est gardee ouverte pendant 65 sec
	keepalive_timeout 65;

    # on definit un serveur web précis, ici https
	server {

        # NGINX ecoute sur port 443 en SSL/TLS en IPv4 (donc les visiteurs arrivent en https)
		listen 443 ssl;

        # pareil mais en IPv6
		listen [::]:443 ssl;

        #nom de dommaine attendu (ex login.42.fr)
		server_name ${DOMAIN_NAME};

        # on autorise seulement TLS 1.2 et TLS 1.3
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_certificate /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;

        #on va chercher les fichiers du site dans ce dossier (endroit ou il y a le volume WP)
		root /var/www/html;
		index index.php index.html index.htm;

        # NGINX va chercher si le chemin est correxct, et envoie vers un vrai fichier
        # si oui il sert le fichier a wordpress (ou a PHP-FPM si le dossier cmprend un index.php)
        #si non il check si le dossier existe
        # si rien n'existe : renvoie interne vers /index.php?$args ==> c'est a WP d'interpreter tout seul
		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {

            # charge les parametres FastCGI standards
			include /etc/nginx/fastcgi_params;

            # fait pour que les fichier .php soient envoye au service Wordpress sur le port 9000 
			fastcgi_pass wordpress:9000;

            # indique a PHP-FPM quel fichier PHP exact doit être execute
            # ex : si root = /var/www/html et qu’on demande /index.php  ==> /var/www/html/index.php
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_param PATH_INFO $fastcgi_path_info;
		}

        # bloque l’acces aux fichiers qui commencent par .ht
		location ~ /\.ht {
			deny all;
		}
	}
}
